services:
  database:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ../.env.development
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "--host", "localhost"]
      interval: 1s
      timeout: 1s
      retries: 300
